#:schema node_modules/wrangler/config-schema.json
name = "chatgpt-telegram-bot-cf"
main = "src/index.ts"
compatibility_date = "2024-10-22"
compatibility_flags = ["nodejs_compat"]

# Workers Logs
[observability]
enabled = true

[vars]
ALLOWED_USERS = "example1"